version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./frontend/vite_fast:/app
    ports:
      - "15173:5173"