version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app_front
    working_dir: /app
    volumes:
      - ./vite_fast:/app
    ports:
      - "15173:5173"